# Generated by Django 3.2.4 on 2021-06-11 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_auto_20210611_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='duratiom',
            new_name='duration',
        ),
    ]
